version: "2"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    ports:
        - "8081:8081"
    command: "npm start"
  database:
    image: "mysql"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD:password 
